# Generated by Django 5.0.6 on 2025-10-11 08:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=140, null=True)),
                (
                    "geometry",
                    models.JSONField(
                        help_text="Original GeoJSON polygon submitted by user"
                    ),
                ),
                (
                    "matrix",
                    models.JSONField(
                        default=list, help_text="2D matrix of tile centroid coordinates"
                    ),
                ),
                ("tile_size_m", models.PositiveIntegerField(default=15)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "Collecting Variables"),
                            ("collected", "Collected"),
                            ("enriching", "Enriching with Gemini"),
                            ("enriched", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="collecting",
                        max_length=20,
                    ),
                ),
                ("processing_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("row_index", models.PositiveIntegerField()),
                ("col_index", models.PositiveIntegerField()),
                ("centroid_lat", models.FloatField()),
                ("centroid_lon", models.FloatField()),
                (
                    "geometry",
                    models.JSONField(help_text="GeoJSON polygon of tile bounds"),
                ),
                ("variables", models.JSONField(default=dict)),
                ("gemini_recommendations", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("collected", "Variables Collected"),
                            ("enriched", "Enriched"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="agro.area",
                    ),
                ),
            ],
            options={
                "ordering": ["row_index", "col_index"],
                "unique_together": {("area", "row_index", "col_index")},
            },
        ),
    ]
